(() => {
  const state = { status:null, pipeline:[], issues:[], prs:[], metrics:null, anomalies:[], config:null, decisions:[], decisionStats:null, tab:'issues', decisionsTab:'recent' };
  const $ = (q, root=document) => root.querySelector(q);
  const $$ = (q, root=document) => [...root.querySelectorAll(q)];
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const duration = seconds => { const n=Number(seconds)||0; if(n<60)return `${n}s`; if(n<3600)return `${Math.round(n/60)}m`; if(n<86400)return `${Math.round(n/3600)}h`; return `${Math.round(n/86400)}d`; };
  const api = async path => { const r=await fetch(`/api/sdlc/${path}`,{headers:{Accept:'application/json'}}); if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`Request failed (${r.status})`); return r.json(); };
  const toast = message => { const el=document.createElement('div'); el.className='toast'; el.textContent=message; $('#toastRegion').append(el); setTimeout(()=>el.remove(),4000); };
  const REPO = 'os-santiago/homedir';
  const titles={overview:'System overview',pipeline:'Pipeline flow',active:'Active items',metrics:'Autonomy & performance',anomalies:'Anomaly detection',audit:'Audit trail',configuration:'Configuration & control',decisions:'Autonomous Decisions'};

  function route(){ const name=location.hash.slice(1)||'overview'; $$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name)); $$('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===name)); $('#pageTitle').textContent=titles[name]||titles.overview; if(!titles[name])location.hash='overview'; }
  function healthClass(status){ return ['healthy','ok','running','idle'].includes(String(status).toLowerCase())?'healthy':['warning','unknown','paused'].includes(String(status).toLowerCase())?'warning':'critical'; }
  function renderStatus(){ const s=state.status;if(!s)return; const worker=s.worker||{}; $('#workerState').textContent=String(worker.state||'unknown').toUpperCase(); $('#lastSync').textContent=`Heartbeat ${duration(worker.heartbeatAge)} ago`; $('#livePulse').className=`live-dot ${healthClass(worker.state)==='healthy'?'ok':'error'}`; const entries=Object.entries(s.components||{}); const good=entries.filter(([,v])=>healthClass(v.status)==='healthy').length; $('#healthScore').textContent=entries.length?`${Math.round(good*100/entries.length)}%`:'--'; $('#componentGrid').classList.remove('loading'); $('#componentGrid').innerHTML=entries.map(([key,c])=>`<article class="component"><div class="component-head"><span class="component-icon">${{scc:'⌁',github:'◉',vps:'▥',webhook:'↯'}[key]||'·'}</span><span class="status ${healthClass(c.status)}">● ${esc(String(c.status||'unknown').toUpperCase())}</span></div><h3>${esc(c.label||key)}</h3><p>${esc(c.detail||metricDetail(c))}</p></article>`).join(''); }
  function metricDetail(c){ if('memory'in c)return `CPU ${Number(c.cpu).toFixed(1)} · Memory ${c.memory}% · Disk ${c.disk}%`; return 'Telemetry available'; }
  function renderPipeline(){ $('#miniPipeline').innerHTML=state.pipeline.map(s=>`<div class="mini-bar" style="height:${Math.max(8,Math.min(100,12+s.count*10))}%" title="${esc(s.name)}: ${s.count}"><span>${esc(s.name.split(' ')[0])}</span></div>`).join(''); $('#pipelineFlow').innerHTML=state.pipeline.map((s,i)=>`<button class="stage ${s.anomalies?'warn':''}" data-stage="${esc(s.id)}"><span class="order">0${i+1}</span><b>${s.count}</b><strong>${esc(s.name)}</strong><small>${duration(s.avgDuration)} average</small></button>`).join(''); $$('[data-stage]').forEach(b=>b.onclick=()=>selectStage(b.dataset.stage)); }
  function selectStage(id){ const s=state.pipeline.find(x=>x.id===id); if(!s)return; $$('.stage').forEach(x=>x.classList.toggle('selected',x.dataset.stage===id)); $('#stageTitle').textContent=s.name; $('#stageMeta').textContent=`${s.count} items · ${duration(s.avgDuration)} average`; $('#stageItems').innerHTML=s.items?.length?table(s.items,'issues'):'<div class="empty">No items currently in this stage.</div>'; }
  function renderAnomalies(){ $('#anomalyBadge').textContent=state.anomalies.length; $('#miniAnomalies').innerHTML=state.anomalies.slice(0,3).map(a=>`<div class="mini-alert"><span class="dot ${a.severity==='critical'?'critical':'warning'}"></span><div><strong>${esc(a.description)}</strong><small>${esc(a.suggestedAction)}</small></div></div>`).join('')||'<div class="empty">No anomalies detected.</div>'; $('#anomalyList').innerHTML=state.anomalies.map(a=>`<article class="anomaly ${esc(a.severity)}"><div><span class="severity">${esc(a.severity.toUpperCase())}</span><time>${new Date(a.timestamp).toLocaleString()}</time></div><div><strong>${esc(a.description)}</strong><p>${esc(a.suggestedAction)}</p></div><span class="pill">${esc(a.affectedResource?.type)} #${esc(a.affectedResource?.number)}</span></article>`).join('')||'<div class="panel empty">All monitored conditions are within their thresholds.</div>'; }
  function table(rows,kind){ const filtered=filterRows(rows); if(!filtered.length)return '<div class="empty">No active items match this filter.</div>'; return `<table><thead><tr><th>RESOURCE</th><th>STATE</th><th>LABELS / CHECKS</th><th>TIME IN STATE</th><th>ESTIMATE</th></tr></thead><tbody>${filtered.map(r=>`<tr><td><a href="${esc(r.githubUrl||'#')}" target="_blank" rel="noopener"><b>#${esc(r.number)}</b> ${esc(r.title)}</a></td><td><span class="status ${healthClass(r.checksStatus||r.state)}">● ${esc(r.checksStatus||r.state||'unknown')}</span></td><td>${kind==='prs'?`<span class="pill">auto-merge ${r.autoMerge?'on':'off'}</span>`:(r.labels||[]).map(l=>`<span class="pill">${esc(typeof l==='string'?l:l.name)}</span>`).join('')}</td><td>${duration(r.ageSeconds)}</td><td>${r.estimatedCompletion?new Date(r.estimatedCompletion).toLocaleTimeString():'—'}</td></tr>`).join('')}</tbody></table>`; }
  function filterRows(rows){ const q=($('#activeSearch')?.value||'').toLowerCase(); return rows.filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q)); }
  function renderActive(){ const rows=state.tab==='issues'?state.issues:state.prs; $('#activeTable').innerHTML=table(rows,state.tab); }
  function renderMetrics(){ const m=state.metrics;if(!m)return; $('#metricCards').innerHTML=[['AUTONOMY',`${m.autonomy}%`,'Without manual intervention'],['AUTO-MERGE',`${m.autoMerge}%`,'Successful merges'],['ISSUE → PR',`${m.performance.issueToPrMinutes}m`,'Average lead time'],['END TO END',`${m.performance.endToEndMinutes}m`,'Issue to closed']].map(x=>`<article class="metric"><span class="kicker">${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join(''); const max=Math.max(1,...m.trend.flatMap(x=>[x.issues,x.merged])); $('#trendChart').innerHTML=m.trend.map((x,i)=>`<div class="bar-group"><i class="bar purple" style="height:${x.issues*100/max}%"></i><i class="bar green" style="height:${x.merged*100/max}%"></i>${i%Math.max(1,Math.floor(m.trend.length/7))===0?`<span>${x.date.slice(5)}</span>`:''}</div>`).join(''); $('#performance').innerHTML=`<article class="panel"><span class="kicker">ADMISSION RATE</span><h3>Decision distribution</h3><p>Accepted <b>${m.admission.accepted}%</b> · Rejected <b>${m.admission.rejected}%</b> · Needs human <b>${m.admission.needsHuman}%</b></p></article><article class="panel"><span class="kicker">SCC DURATION</span><h3>By complexity</h3><p>Simple <b>${m.performance.sccByComplexity.simple}m</b> · Medium <b>${m.performance.sccByComplexity.medium}m</b> · Complex <b>${m.performance.sccByComplexity.complex}m</b></p></article>`; }
  function renderConfig(){ const c=state.config;if(!c)return; $('#footerVersion').textContent=c.workerVersion; $('.danger-panel').hidden=!c.controlsEnabled; $('#configGrid').innerHTML=`<dl class="config-card"><dt>STATE DIRECTORY</dt><dd>${esc(c.stateDirectory)}</dd><dt>WORKER VERSION</dt><dd>${esc(c.workerVersion)}</dd></dl><dl class="config-card"><dt>PIPELINE LABELS</dt><dd>${(c.labels||[]).map(esc).join('<br>')}</dd></dl><dl class="config-card"><dt>TIMEOUTS</dt><dd>Heartbeat: ${duration(c.timeouts?.heartbeatSeconds)}<br>Admission: ${duration(c.timeouts?.admissionSeconds)}</dd><dt>CURRENT MODE</dt><dd><span class="status ${c.paused?'warning':'healthy'}">● ${c.paused?'PAUSED':'ACTIVE'}</span></dd></dl>`; }
  function renderDecisions(){ const tab=state.decisionsTab; if(tab==='recent')renderRecentDecisions(); else renderDecisionStats(); }
  function renderRecentDecisions(){ const decisions=state.decisions||[]; $('#decisionsContent').innerHTML=decisions.slice(0,50).map(d=>`<article class="decision-card ${d.needsReview?'needs-review':''}"><div class="decision-header"><span class="decision-category ${esc((d.category||'').toLowerCase())}">${esc(d.category)}</span><span class="decision-confidence">${esc(d.confidence)}</span><time>${new Date(d.timestamp).toLocaleString()}</time></div><h3>${esc(d.decision)}</h3><p><strong>Rationale:</strong> ${esc(d.rationale)}</p><p><strong>Pattern:</strong> ${esc(d.pattern)}</p><p><strong>Reversible:</strong> ${esc(d.reversibility)}</p><div class="decision-footer"><a href="https://github.com/${REPO}/issues/${d.issueNumber}" target="_blank">#${d.issueNumber}</a>${d.prNumber?`<a href="https://github.com/${REPO}/pull/${d.prNumber}" target="_blank">PR #${d.prNumber}</a>`:''}</div></article>`).join('')||'<div class="panel empty">No autonomous decisions recorded yet.</div>'; }
  function renderDecisionStats(){ const stats=state.decisionStats;if(!stats)return; const categories=Object.entries(stats.byCategory||{}).map(([k,v])=>`<div class="stat-row"><span>${esc(k)}</span><b>${v}</b></div>`).join(''); const confidence=Object.entries(stats.byConfidence||{}).map(([k,v])=>`<div class="stat-row"><span>${esc(k)}</span><b>${v}</b></div>`).join(''); $('#decisionsContent').innerHTML=`<div class="split"><article class="panel"><h3>Overview</h3><div class="metric-grid"><article class="metric"><span class="kicker">TOTAL</span><strong>${stats.total}</strong><small>Autonomous decisions</small></article><article class="metric"><span class="kicker">AUTONOMY RATE</span><strong>${stats.autonomyRate}%</strong><small>High-confidence decisions</small></article><article class="metric"><span class="kicker">NEEDS REVIEW</span><strong>${stats.needsReview}</strong><small>Low confidence or high risk</small></article></div></article><article class="panel"><h3>By Category</h3>${categories}</article></div><article class="panel"><h3>By Confidence</h3>${confidence}</article>`; }
  async function load(showToast=false){ try{ const data=await api('snapshot'); const range=String($('#range')?.value||30); const decisions=await api('autonomous-decisions').catch(()=>[]); const decisionStats=await api('autonomous-decisions/stats').catch(()=>null); Object.assign(state,{status:data.status,pipeline:data.pipeline||[],issues:data.issues||[],prs:data.prs||[],metrics:data.metricsByRange?.[range]||data.metrics,metricsByRange:data.metricsByRange||{},anomalies:data.anomalies||[],config:data.configuration,decisions,decisionStats}); renderStatus();renderPipeline();renderActive();renderMetrics();renderAnomalies();renderConfig();renderDecisions(); if(showToast)toast(data.stale?'Serving the last telemetry snapshot':'Telemetry refreshed'); }catch(e){ $('#workerState').textContent='DISCONNECTED';$('#livePulse').className='live-dot error';toast(e.message); } }
  async function audit(id){ const box=$('#auditTimeline');box.className='timeline';box.innerHTML='<div class="empty">Loading events…</div>';try{const rows=await api(`audit/${encodeURIComponent(id)}`);box.innerHTML=rows.map(e=>`<article class="event"><h3>${esc(e.decision||e.eventType||'Worker event')}</h3><small>${new Date(e.timestamp||e.created_at).toLocaleString()} · ${esc(e.actor||'worker')}</small><p>${esc(e.reasoning||e.detail||'No additional context recorded.')}</p></article>`).join('')||'<div class="panel empty">No audit events were found for this resource.</div>';}catch(e){box.innerHTML=`<div class="panel empty">${esc(e.message)}</div>`;} }
  async function control(action){ if(!confirm(`Confirm “${action}”? This administrative action will be audited.`))return;try{const r=await fetch(`/api/sdlc/control/${action}`,{method:'POST',headers:{Accept:'application/json'}});const body=await r.json();if(!r.ok)throw new Error(body.error||'Action failed');toast(`Action completed: ${action}`);await load();}catch(e){toast(e.message);} }
  addEventListener('hashchange',route); $('#refresh').onclick=()=>load(true); $('#activeSearch').oninput=renderActive; $$('.tabs button').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));renderActive();}); $('#range').onchange=()=>{state.metrics=state.metricsByRange?.[$('#range').value]||state.metrics;renderMetrics();}; $('#auditForm').onsubmit=e=>{e.preventDefault();audit($('#auditId').value)}; $$('.controls button').forEach(b=>b.onclick=()=>control(b.dataset.action)); route();load();setInterval(load,30000);
})();
