{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.ghToken }}
  GH_TOKEN: {{ .Values.secrets.ghToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.nvidiaApiKey }}
  NVIDIA_API_KEY: {{ .Values.secrets.nvidiaApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
