apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "implementation.fullname" . }}
  labels:
    {{- include "implementation.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "implementation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "implementation.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "implementation.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.config.port }}
          protocol: TCP
        env:
        - name: PORT
          value: {{ .Values.config.port | quote }}
        - name: SC_AGENT_PATH
          value: {{ .Values.config.scAgent.path | quote }}
        - name: SC_PROFILE
          value: {{ .Values.config.scAgent.profile | quote }}
        - name: MAX_IMPLEMENTATION_ITERATIONS
          value: {{ .Values.config.quality.maxIterations | quote }}
        - name: QUALITY_THRESHOLD
          value: {{ .Values.config.quality.threshold | quote }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        {{- if .Values.scAgentConfig.create }}
        - name: sc-agent-config
          mountPath: /home/appuser/.config/sc-agent
          readOnly: true
        {{- end }}
      volumes:
      {{- if .Values.scAgentConfig.create }}
      - name: sc-agent-config
        configMap:
          name: {{ include "implementation.fullname" . }}-scagent
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
