FROM mcr.microsoft.com/playwright@sha256:bc6ab0d6d44ff4826e4cb8c1e6d801e185bfc42bb0753f8e2a30efc70db054c7
WORKDIR /opt/validator
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts --omit=dev && npm cache clean --force
COPY check.cjs ./
USER 10000:10000
ENTRYPOINT ["node", "/opt/validator/check.cjs"]
